server:
  port: 8081
spring:
  application:
    name: tlq-cn-demo

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha


tlqcn:
  client:
    service-url: tlqcn://10.10.22.133:6550
    service-http-url: http://10.10.22.133:8580
    failover-config:
      primary-url: tlqcn://10.10.22.174:6650
      primary-http-url: http://10.10.22.174:8080
      secondary-url: tlqcn://10.10.22.175:6650
      secondary-http-url: http://10.10.22.175:8080
  Rot-test-config:
    url: 10.10.22.136:19876
  Aot-test-config:
    url: 10.10.22.174:5682,10.10.22.174:5682
  Kot-test-config:
    url: 10.10.22.174:9092,10.10.22.175:9092
  Mot-test-config:
    url: tcp://10.10.22.174:1883,tcp://10.10.22.175:1883
  Jms-test-config:
    broker-service-url: pulsar://10.10.22.174:6650,10.10.22.175:6650
    web-service-url: http://10.10.22.162:8080,10.10.22.174:8080